Models/JobApplication.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Appli.Models
{
    public class JobApplication
    {
        [Key]
        public int Id { get; set; }

        [NotMapped]
        private DateTime? _nextInterview = null;

        [Required]
        public string UserId { get; set; }

        public ApplicationUser User { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime DateCreated { get; set; }

        [Display(Name = "Company Name")]
        [StringLength(30)]
        [Required]
        public string CompanyName { get; set; }

        [Display(Name = "Position")]
        [StringLength(30)]
        [Required]
        public string Position { get; set; }

        public int? RecruiterId { get; set; }

        public Recruiter Recruiter { get; set; }

        [Display(Name = "Position Link")]
        public string PositionLink { get; set; }

        [Display(Name = "Rejected")]
        public bool Rejected { get; set; }

        [Display(Name = "Offer")]
        public string Offer { get; set; }

        [Display(Name = "Last Contact")]
        [DataType(DataType.Date)]
        public DateTime LastContact { get; set; }

        [Display(Name = "Notes")]
        [StringLength(300)]
        public string Notes { get; set; }

        [Display(Name = "Still Active?")]
        [DefaultValue(true)]
        public bool IsActive { get; set; }
        public virtual ICollection<Interview> Interviews { get; set; }

        [NotMapped]
        [Display(Name = "Next Interview")]
        public DateTime? NextInterview
        {
            get
            {
                if (Interviews == null)
                {
                    return null;
                }
                foreach (Interview i in Interviews)
                {

                    if (i.Date >= DateTime.Now.Date && i.Date <= _nextInterview)
                    {
                        _nextInterview = i.Date;
                    }
                    else if (i.Date >= DateTime.Now.Date)
                    {
                        _nextInterview = i.Date;
                    }
                }
                return _nextInterview;
            }
        }
    }
}

Controllers/InterviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Appli.Data;
using Appli.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Appli.Controllers
{
    [Authorize]
    public class InterviewsController : Controller
    {
        private readonly ApplicationDbContext _context;
        //private readonly UserManager<ApplicationUser> _userManager;

        public InterviewsController(ApplicationDbContext context/*, UserManager<ApplicationUser> userManager*/)
        {
            _context = context;
            //_userManager = userManager;

        }

        // GET: Interviews
        public async Task<IActionResult> Index(int? id)
        {
            var applicationDbContext = await _context.Interview
                .Include(i => i.JobApplication)
                .Where(i => i.JobApplicationId == id)
                .ToListAsync();
            if (applicationDbContext.Count == 0)
            {
                return RedirectToAction(nameof(Create), new { JobApplicationId = id });
            }
            return View(applicationDbContext);
        }

        // GET: Interviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interview = await _context.Interview
                .Include(i => i.JobApplication)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (interview == null)
            {
                return NotFound();
            }

            return View(interview);
        }

        // GET: Interviews/Create
        public IActionResult Create(int? JobApplicationId)
        {

            ViewData["JobApplicationId"] = JobApplicationId;
            return View();
        }

        // POST: Interviews/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,JobApplicationId,Date,Address,Notes")] Interview interview)
        {
            if (ModelState.IsValid)
            {
                _context.Add(interview);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = interview.JobApplicationId });
            }
            ViewData["JobApplicationId"] = new SelectList(_context.JobApplication, "Id", "CompanyName", interview.JobApplicationId);
            return View(interview);
        }

        // GET: Interviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interview = await _context.Interview.FindAsync(id);
            if (interview == null)
            {
                return NotFound();
            }
            ViewData["JobApplicationId"] = new SelectList(_context.JobApplication, "Id", "CompanyName", interview.JobApplicationId);
            return View(interview);
        }

        // POST: Interviews/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,JobApplicationId,Date,Address,Notes")] Interview interview)
        {
            if (id != interview.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(interview);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InterviewExists(interview.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { id = interview.JobApplicationId});
            }
            ViewData["JobApplicationId"] = new SelectList(_context.JobApplication, "Id", "CompanyName", interview.JobApplicationId);
            return View(interview);
        }

        // GET: Interviews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interview = await _context.Interview
                .Include(i => i.JobApplication)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (interview == null)
            {
                return NotFound();
            }

            return View(interview);
        }

        // POST: Interviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var interview = await _context.Interview.FindAsync(id);
            _context.Interview.Remove(interview);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id = interview.JobApplicationId });
        }

        private bool InterviewExists(int id)
        {
            return _context.Interview.Any(e => e.Id == id);
        }
    }
}

Controllers/JobApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Appli.Data;
using Appli.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Appli.Controllers
{
    [Authorize]
    public class JobApplicationsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public JobApplicationsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: JobApplications
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var applicationDbContext = _context.JobApplication
                .Include(j => j.Recruiter)
                .Include(j => j.Interviews)
                .Include(j => j.User)
                .Where(j => j.UserId == user.Id); 
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: JobApplications/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var jobApplication = await _context.JobApplication
                .Include(j => j.Recruiter)
                .Include(j => j.Interviews)
                .Include(j => j.User)
                .Where(j => j.UserId == user.Id)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jobApplication == null)
            {
                return NotFound();
            }

            return View(jobApplication);
        }

        // GET: JobApplications/Create
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var recruiterList = new SelectList(_context.Recruiter
                .Where(r => r.UserId == user.Id) 
                .Where(r => r.IsActive == true), "Id", "FullName")
                .ToList();
            recruiterList.Insert(0, new SelectListItem
            {
                Text = "Select Recruiter",
                Value = "null"
            });
            ViewData["RecruiterId"] = recruiterList; return View();
        }

        // POST: JobApplications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,DateCreated,CompanyName,Position,RecruiterId,PositionLink,Rejected,Offer,LastContact,Notes,IsActive")] JobApplication jobApplication)
        {
            if (jobApplication.RecruiterId.ToString() == "null")
            {
                jobApplication.RecruiterId = null;
            }

            ModelState.Remove("UserId");
            ModelState.Remove("RecruiterId");
            ModelState.Remove("IsActive");
            if (ModelState.IsValid)
            {
                var user = await GetUserAsync();
                jobApplication.UserId = user.Id;
                jobApplication.IsActive = true;
                _context.Add(jobApplication);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            var recruiterList = new SelectList(_context.Recruiter
                .Where(r => r.IsActive == true), "Id", "FullName")
                .ToList();
            recruiterList.Insert(0, new SelectListItem
            {
                Text = "Select Recruiter",
                Value = "null"
            });
            ViewData["RecruiterId"] = recruiterList;
            return View(jobApplication);
        }

        // GET: JobApplications/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplication
               .Include(j => j.Interviews)
               .FirstOrDefaultAsync(m => m.Id == id);
            if (jobApplication == null)
            {
                return NotFound();
            }
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var recruiterList = new SelectList(_context.Recruiter
                .Where(r => r.UserId == user.Id)
                .Where(r => r.IsActive == true), "Id", "FullName")
                .ToList();
            recruiterList.Insert(0, new SelectListItem
            {
                Text = "Select Recruiter",
                Value = "null"
            });
            ViewData["RecruiterId"] = recruiterList;
            return View(jobApplication);
        }

        // POST: JobApplications/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,DateCreated,CompanyName,Position,RecruiterId,PositionLink,Rejected,Offer,LastContact,Notes,IsActive")] JobApplication jobApplication)
        {
            if (jobApplication.RecruiterId.ToString() == "null")
            {
                jobApplication.RecruiterId = null;
            }

            if (id != jobApplication.Id)
            {
                return NotFound();
            }

            ModelState.Remove("UserId");
            ModelState.Remove("RecruiterId");
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await GetUserAsync();
                    jobApplication.UserId = user.Id;
                    _context.Update(jobApplication);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobApplicationExists(jobApplication.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            var recruiterList = new SelectList(_context.Recruiter
                .Where(r => r.IsActive == true), "Id", "FullName")
                .ToList();
            recruiterList.Insert(0, new SelectListItem
            {
                Text = "Select Recruiter",
                Value = "null"
            });
            ViewData["RecruiterId"] = recruiterList;
            return View(jobApplication);
        }

        // GET: JobApplications/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplication
                .Include(j => j.Recruiter)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (jobApplication == null)
            {
                return NotFound();
            }

            return View(jobApplication);
        }

        // POST: JobApplications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var jobApplication = await _context.JobApplication.FindAsync(id);
            _context.JobApplication.Remove(jobApplication);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        private bool JobApplicationExists(int id)
        {
            return _context.JobApplication.Any(e => e.Id == id);
        }

        private Task<ApplicationUser> GetUserAsync()
        {
            return _userManager.GetUserAsync(HttpContext.User);
        }
    }
}

Views/JobApplications/Details.cshtml
@model Appli.Models.JobApplication

@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>JobApplication</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Recruiter)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Recruiter.EmailAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PositionLink)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PositionLink)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NextInterview)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NextInterview)
        </dd>
        <dt class="col-sm-2">
            <a asp-controller="Interviews" asp-action="Index" asp-route-id="@Model.Id">All Interviews</a>
        </dt>
        <dd class="col-sm-10">
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Offer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Offer)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastContact)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastContact)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rejected)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rejected)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>

Views/JobApplications/Edit.cshtml
@model Appli.Models.JobApplication

@{
    ViewData["Title"] = "Edit";
}

<h4>Application</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>

            <a asp-controller="Interviews" asp-action="Index" asp-route-id="@Model.Id">Edit Interviews</a>

            <div class="form-group">
                <label asp-for="RecruiterId" class="control-label"></label>
                <select asp-for="RecruiterId" class="form-control" asp-items="ViewBag.RecruiterId"></select>
                <span asp-validation-for="RecruiterId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PositionLink" class="control-label"></label>
                <input asp-for="PositionLink" class="form-control" />
                <span asp-validation-for="PositionLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Offer" class="control-label"></label>
                <input asp-for="Offer" class="form-control" />
                <span asp-validation-for="Offer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastContact" class="control-label"></label>
                <input asp-for="LastContact" class="form-control" />
                <span asp-validation-for="LastContact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Rejected" /> @Html.DisplayNameFor(model => model.Rejected)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/JobApplications/Index.cshtml
@model IEnumerable<Appli.Models.JobApplication>

@{
    ViewData["Title"] = "Index";
}
<h4>Application History</h4>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table table-hover">
    <thead class="jobApp border-primary">
        <tr class="table-info">
            <th scope="col">
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Recruiter)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.PositionLink)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.NextInterview)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Offer)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.LastContact)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            @if (item.IsActive == false)
            {
                <tr class="jobApp table-active">
                    <td>
                        @Html.DisplayFor(modelItem => item.CompanyName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Position)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Recruiter.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PositionLink)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NextInterview)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Offer)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastContact)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
            else if (item.Rejected == true)
            {
                <tr class="jobApp table-danger">
                    <td>
                        @Html.DisplayFor(modelItem => item.CompanyName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Position)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Recruiter.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PositionLink)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NextInterview)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Offer)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastContact)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
            else if (item.NextInterview != null)
            {
                @if (item.NextInterview.Value.AddDays(-2) <= DateTime.Now)
                {
                    <div class="alert alert-dismissible alert-success">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <h4 class="alert-heading">You've got an interview coming up!</h4>
                        <p class="mb-0">Don't forget your interview with @item.CompanyName | @item.NextInterview!</p>
                        <p class="mb-0">@item.Notes</p>
                    </div>
                }
                <tr class="jobApp table-success">
                    <td>
                        @Html.DisplayFor(modelItem => item.CompanyName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Position)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Recruiter.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PositionLink)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NextInterview)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Offer)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastContact)
                    </td>
                    <td>
                        <a asp-controller="JobApplications" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-controller="JobApplications" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-controller="JobApplications" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }

            else if (item.LastContact.AddDays(7) < DateTime.Now)
            {
                <div class="alert alert-dismissible alert-primary">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <h4 class="alert-heading">Have you heard from @item.CompanyName?</h4>
                    <p class="mb-0">If not, this is a good time to reach out! </p>
                </div>
                <tr class="jobApp table-primary">
                    <td id="company-name">
                        @Html.DisplayFor(modelItem => item.CompanyName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Position)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Recruiter.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PositionLink)
                    </td>
                    <td id="index-alert">
                        <b>Time to follow up...</b>
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Offer)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastContact)
                    </td>
                    <td>
                        <a asp-controller="JobApplications" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-controller="JobApplications" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-controller="JobApplications" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }

            else
            {
                <tr class="jobApp table-warning">
                    <td>
                        @Html.DisplayFor(modelItem => item.CompanyName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Position)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Recruiter.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PositionLink)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NextInterview)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Offer)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastContact)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>